language: node_js
node_js:
  - "node"
  - "10"
  - "8"
  - "lts/*"
before_install: "cd ./connect-api"
before_script: "cd ./connect-api"
before_deploy: "cd ./connect-api"
deploy:
  provider: npm
  email: $DEPLOY_NPM_EMAIL
  api_key: $DEPLOY_NPM_API_KEY
  skip_cleanup: true
